//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNO()
        {
            this.ALUMNO_CLASE = new HashSet<ALUMNO_CLASE>();
        }
    
        public int ID_ALUMNO { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
        public string NOMBRE_ALUMNO { get; set; }
        public string AP_ALUMNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUMNO_CLASE> ALUMNO_CLASE { get; set; }
        public virtual CARRERA CARRERA { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
