//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_CURSO
    {
        public int ID_HISTORIAL { get; set; }
        public Nullable<int> ID_CLASE { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> NUMERO_CLASE { get; set; }
    
        public virtual CLASE CLASE { get; set; }
        public virtual ESTADO_CLASE ESTADO_CLASE { get; set; }
    }
}
