//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO_SALA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODULO_SALA()
        {
            this.CLASE = new HashSet<CLASE>();
        }
    
        public Nullable<int> ID_SALA { get; set; }
        public Nullable<int> ID_MODULO { get; set; }
        public int ID_MODULO_SALA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASE> CLASE { get; set; }
        public virtual MODULO MODULO { get; set; }
        public virtual SALA SALA { get; set; }
    }
}
