//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRERA_RAMO
    {
        public Nullable<int> ID_RAMO { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public int ID_CARRERA_RAMO { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual RAMO RAMO { get; set; }
    }
}
