//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clasesEntities : DbContext
    {
        public clasesEntities()
            : base("name=clasesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ALUMNO_CLASE> ALUMNO_CLASE { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<CARRERA_RAMO> CARRERA_RAMO { get; set; }
        public virtual DbSet<CLASE> CLASE { get; set; }
        public virtual DbSet<ESTADO_CLASE> ESTADO_CLASE { get; set; }
        public virtual DbSet<HISTORIAL_CURSO> HISTORIAL_CURSO { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<MODULO_SALA> MODULO_SALA { get; set; }
        public virtual DbSet<PROFESOR> PROFESOR { get; set; }
        public virtual DbSet<RAMO> RAMO { get; set; }
        public virtual DbSet<RAMO_PROFESOR> RAMO_PROFESOR { get; set; }
        public virtual DbSet<RAMO_SECCION> RAMO_SECCION { get; set; }
        public virtual DbSet<SALA> SALA { get; set; }
        public virtual DbSet<SECCION> SECCION { get; set; }
        public virtual DbSet<SECCION_MODULO> SECCION_MODULO { get; set; }
        public virtual DbSet<SECCION_PROFESOR> SECCION_PROFESOR { get; set; }
    }
}
