//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAMO()
        {
            this.CARRERA_RAMO = new HashSet<CARRERA_RAMO>();
            this.RAMO_PROFESOR = new HashSet<RAMO_PROFESOR>();
            this.RAMO_SECCION = new HashSet<RAMO_SECCION>();
        }
    
        public int ID_RAMO { get; set; }
        public string NOMBRE_RAMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRERA_RAMO> CARRERA_RAMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAMO_PROFESOR> RAMO_PROFESOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAMO_SECCION> RAMO_SECCION { get; set; }
    }
}
