//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECCION_MODULO
    {
        public Nullable<int> ID_MODULO { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
        public int ID_MODULO_SECCION { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
